### ISSUE TITLE
Mountpoint for config folder

### ISSUE THREAD

**Issue by biglobe** [crate/docker-crate#120]
Hi, I'm not sure how the entire docker thing works, however can I suggest that the /crate/config folder be available as a mountpoint in docker manifest file?

**Comment by autophagy** [comment]
@biglobe You should be able to mount a crate config file, like:
```
network.host: _local_,_site_

cluster.name: "test_cluster"

# Paths
path:
  logs: /data/log
  data: /data/data
blobs:
  path: /data/blobs
```

via `docker run -v /path/to/crate.yml:/crate/config/crate.yml crate/crate:latest`, and it will use the config file you supply rather than the default one included in the container. Unless I misunderstand your suggestion?
