### ISSUE TITLE
2.0.2 gives connection reset

### ISSUE THREAD

**Issue by martinrm77** [crate/docker-crate#78]
Starting a cratedb in docker and then connecting via curl gives connection reset. Tried on different servers, same result.

I run container with following command:
docker run --name crate -d --memory 2g --env CRATE_HEAP_SIZE=1g -v /srv/crate:/data -p 4200:4200 -p 4300:4300 crate crate -Ccluster.name=cluster -Clicense.enterprise=false

And get following results when trying to access it per documentation:
# curl -i localhost:4200/admin
curl: (56) Recv failure: Connection reset by peer

**Comment by martinrm77** [comment]
ok, one needs to include -Cnetwork.host=_site_ - then it works.
Very confusing documentation...

There are multiple examples with just docker run and I can find only one with network.publish_host:_site_

You should update documentation or change default from _local_ to _site_

**Comment by joemoe** [comment]
thanks @martinrm77, we will improve that.

**Comment by k0pernikus** [comment]
If someone is interested how to apply that fix with docker-compose:

```
crate:
   image: crate/crate
   ports:
       - "4200:4200"
       - "4230:4230"
   entrypoint:
       - /docker-entrypoint.sh
       - crate
       - -Cnetwork.host=_site_
       - -Clicense.enterprise=false
   environment:
       CRATE_HEAP_SIZE: 128m
       JAVA_OPTS: '-Xmx1g'
```
I also had to run on my host machine (Ubuntu 16.04):

    sudo sysctl -w vm.max_map_count=262144
